version: '3.8'

services:
  postgres:
    container_name: postgres-db
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=genixo
      - POSTGRES_PASSWORD=genixo
    ports:
      - '5432:5432'
    volumes:
      - /root/db_files:/var/lib/postgresql/data
    networks:
      - atlas-network


networks:
  atlas-network:
    name: atlas-network