spring:
  profiles:
    active: auto-db-create
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  datasource:
    dbName: atlas_db
    dbUrl: jdbc:postgresql://localhost:5432/ #3
    #dbUrl: jdbc:postgresql://postgres:5432/

    url: ${spring.datasource.dbUrl}${spring.datasource.dbName}
    username: genixo
    password: genixo
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: MyHikariCP
      transaction-isolation: TRANSACTION_READ_COMMITTED
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true

  flyway:
    baselineOnMigrate: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    url: ${spring.datasource.dbUrl}${spring.datasource.dbName}
    locations:
      - classpath:/db/script
    enabled: false



  # Multipart ayarlar? buraya ta??nd?
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

management:
  endpoints:
    web:
      base-path: /actuator

server:
  servlet:
    context-path: /api
  # Tomcat ayarlar? eklendi
  tomcat:
    max-swallow-size: 1GB
    max-http-form-post-size: 1GB

storage:
  base: /app/uploads/
  #base: /Users/developer/Desktop/file/

application:
  security:
    jwt:
      secret-key: uLO6QrqPEmyHZfU1jR3vS8wX2nKgT4iN9bAcDhMkVpYe7tWsJxG5aFdB0CzI4nPmQvUyL8kR3wT9
      expiration: 31536000000
      refresh-token:
        expiration: 31536000000




  #logging:
  #  level:
  #    root: DEBUG
  #    com.sizinpaketadiniz: DEBUG
  #    org.springframework.web: DEBUG